#################
### AUTOSTART ###
#################

exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

exec_always sh -c "pkill -x waybar; waybar"
exec_always sh -c "pkill -x autotiling; autotiling"
exec_always sh -c "pkill -f battery-notify.sh; ~/.config/sway/scripts/battery-notify.sh"

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec mako
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
