##################
### DECORATION ###
##################

font pango:0xProto Nerd Font 9

gaps inner 5
gaps outer 0
default_floating_border pixel 2
default_border pixel 2

set $main #7AA2F7
set $text #e1e1f5
set $back #1a1b26

client.focused          $main $back $text $main $main
client.focused_inactive #565f89 #1a1b26 #a9b1d6 #565f89 #565f89
client.unfocused        #3b3d57 #1a1b26 #565f89 #3b3d57 #3b3d57
