##################
### DECORATION ###
##################

font pango:0xProto Nerd Font 9

gaps inner 10
default_floating_border pixel 2
default_border pixel 2

set $main #7AA2F7
set $fg #ffffff
set $text #e1e1f5
set $back #1a1b26

client.focused          $main $back $text $main $main
client.focused_inactive $fg $back $text $fg $fg
client.unfocused        $fg $back $text $fg $fg
