##############
### OUTPUT ###
##############

output eDP-1 resolution 1366x768 position 0,0 scale 1
output * background ~/.wallpapers/ganyu.png fill

seat seat0 xcursor_theme Bibata-Modern-Ice 24

input "1267:12587:ELAN050B:01_04F3:312B_Touchpad" {
    tap enabled
    natural_scroll enabled
    dwt enabled
    accel_profile adaptive
    middle_emulation enabled
    pointer_accel 0.3
    scroll_factor 0.8
}
