################
### FLOATING ###
################

for_window [title=".*(Open Folder|Rename|File Operation Progress|Confirm to replace files|Extract|Compress|save).*"] floating enable
for_window [app_id="ristretto"] floating enable
for_window [app_id="zenity"] floating enable
for_window [title="^Steam Settings$"] floating enable

for_window [app_id="zenity"] resize set 900 600
