################
### VARIABLE ###
################

set $mod Mod4
set $alt Mod1

# Vim-style movement
set $left h
set $down j
set $up k
set $right l

# Programs
set $term foot
set $browser chromium
set $filemanager foot fish -C "y"
