[main]
shell=/bin/fish
font=0xProto Nerd Font Mono:size=11:weight=bold
font-italic=0xProto Nerd Font Mono:size=11:slant=italic
pad=1x4
title=foot
app-id=foot

[cursor]
style=beam
blink=yes
blink-rate=500

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000
indicator-position=relative
indicator-format=percentage

[url]
launch=xdg-open ${url}

[colors-dark]
alpha=1.0
foreground=c0caf5
background=1a1b26
selection-foreground=c0caf5
selection-background=283457
urls=73daca
flash=7f5f00
# Black
regular0=15161e
bright0=414868
# Red
regular1=f7768e
bright1=f7768e
# Green
regular2=9ece6a
bright2=9ece6a
# Yellow
regular3=e0af68
bright3=e0af68
# Blue
regular4=7aa2f7
bright4=7aa2f7
# Magenta
regular5=bb9af7
bright5=bb9af7
# Cyan
regular6=7dcfff
bright6=7dcfff
# White
regular7=a9b1d6
bright7=c0caf5

16=ff9e64
17=db4b4b
