[mgr]
prepend_keymap = [
    { on = [ "g", "p" ], run = "cd ~/Projects/Programming/", desc = "Go ~/Projects/Programming" },

    # Compress
    { on = [ "C" ], run = "plugin ouch", desc = "Compress" },

    # Trash
    { on = "u", run = "plugin recycle-bin restore", desc = "Restore deleted files" },
    { on = "R", run = "plugin omni-trash", desc = "Open Trash menu" },
    { on = [ "g", "t" ], run = "cd ~/.local/share/Trash/files", desc = "Go to Trash folder" },

    # Mount
    { on = "M", run = "plugin mount", desc = "Mount devices" },

    # Terminal
    { on = "T", run = 'shell "foot" --orphan --confirm', desc = "Open foot terminal" },

    # Filter
    { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
]
